### ISSUE TITLE
Respx.mock(...) decorator on test bug

### ISSUE THREAD

**Issue by SlavaSkvortsov** [lundberg/respx#100]
Hi! You did a nice job with refactoring, I really like it! 

I found a bug and I have no idea how to fix it correctly. 
```python
@respx.mock(base_url='https://foo.bar')
def test_base_url_with_decorator(respx_mock: MockTransport):
    respx_mock.get('buzz')

    with httpx.Client() as client:
        client.get('https://foo.bar/buzz')

    respx_mock.calls.assert_called_once()
```

If you try to execute it you'll get an error:
```
  @respx.mock(base_url='https://foo.bar')
  def test_base_url_with_decorator(respx_mock: MockTransport):
E       fixture 'respx_mock' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, cov, doctest_namespace, event_loop, mocked_foo, mocked_ham, monkeypatch, my_mock, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, unused_tcp_port, unused_tcp_port_factory
>       use 'pytest --fixtures [testpath]' for help on them.
```

The only idea I have is to create respx_mock a fixture (it will allow using respx like `monkeypatch` fixture) and tie it with the decorator.

**Comment by lundberg** [comment]
> Hi! You did a nice job with refactoring, I really like it!
Thanks!

> I found a bug and I have no idea how to fix it correctly.
Hmm, thats weird...

[This test](https://github.com/lundberg/respx/blob/master/tests/test_mock.py#L245-L246) should cover this specific case. [This one](https://github.com/lundberg/respx/blob/master/tests/test_mock.py#L218-L220) as well.

Could it be that `pytest` needs a `None` default, to not treat it as a fixture?
```py
@respx.mock(base_url='https://foo.bar')
def test_base_url_with_decorator(respx_mock: MockTransport = None):
    ...                                                    #  ^
```

**Comment by lundberg** [comment]
@SlavaSkvortsov, any news on this one?
