### ISSUE TITLE
Add a files pattern?

### ISSUE THREAD

**Issue by lundberg** [lundberg/respx#115]
As mentioned in #87, it might be of interest to allow matching a request on files being sent.

- What do we want to match on?
- Is it even possible once internal `HTTPX` request is built.

```py
route = respx.post("https://example.org/", files=?)
```

Since uploading files with `HTTPX` supports multiple arg types, it might *only* be possible to match on file names, if given. Reading a file object's content could affect `HTTPX` internals, if not handled properly, like reseting seek point etc.

Needs further investigation, [multiple files](https://github.com/encode/httpx/pull/1032/files).

**Comment by ziima** [comment]
I used this utility function to extract files from the `httpx.Request` in tests:

```python
import email
from httpx import Request
from typing import Any, Dict

def _get_data(request: Request) -> Dict[str, Any]:
    raw_data = (
        b'MIME-Version: 1.0\nContent-Type: '
        + request.headers['Content-Type'].encode(request.headers.encoding)
        + b'\n\n' + request.read())
    msg = email.message_from_bytes(raw_data)
    data = {}
    for payload in msg.get_payload():
        key = payload.get_param('name', header='Content-Disposition')
        decode = payload.get_content_maintype().startswith('application')
        data[key] = payload.get_payload(decode=decode)
    return data
```
