### ISSUE TITLE
How to get the json a call was made with?

### ISSUE THREAD

**Issue by surfer190** [lundberg/respx#127]
Hi, I can get the content of the request but not as json. Is this part of the api?

```
my_mock.calls[0].request.content 
b'{"extra_vars": {"name": "TEST"}'
```

**Comment by lundberg** [comment]
The `request` object is not RESPX, it's the `HTTPX` model which unfortunately doesn't have that api.

However, if your intension is to assert a certain json body was posted, then you can use the RESPX [json pattern](https://lundberg.github.io/respx/api/#json) to match on that specific body (or nested value) and mock whatever suits the test.

```py
respx.post("https://example.org/", json__extra_vars__name="TEST").respond(201)
response = httpx.post("https://example.org/", json={"extra_vars": {"name": "TEST"})
assert response.status_code == 201
```
This example will only mock the status code `201` for requests posting that nested json value posted.

**Comment by surfer190** [comment]
Thanks I will try your suggestion
