### ISSUE TITLE
RuntimeError when trying to mock httpx Response with async stream

### ISSUE THREAD

**Issue by jreiberkyle** [lundberg/respx#130]
When I try to mock a httpx Response with an async stream using respx, I get the following error:

`RuntimeError: Attempted to call a sync iterator on an async stream.`

I am running python 3.7.9, pytest 6.2.1, pytest-asyncio 0.14.0, httpx 0.16.1, respx 0.16.3

To replicate:

test_httpx.py
```
import httpx
import pytest
import respx


@respx.mock
@pytest.mark.asyncio
async def test_async_stream(tmpdir):
    dl_url = 'http://MockNotRealURL/download/?token=IAmAToken'

    img_headers = {
        'Content-Type': 'image/tiff',
        'Content-Length': '6',
        'Content-Disposition': 'attachment; filename="img.tif"'
    }

    async def _stream_img():
        yield b'bld'
        yield b'dce'

    mock_resp = httpx.Response(200, stream=_stream_img(), headers=img_headers)
    respx.get(dl_url).return_value = mock_resp

    filename = tmpdir / 'img.tif'

    async with httpx.AsyncClient() as cl:
        async with cl.stream('GET', dl_url) as resp:
            with open(filename, 'wb') as fp:
                async for chunk in resp.aiter_bytes():
                    fp.write(chunk)
```

Full traceback
```
>           async with cl.stream('GET', dl_url) as resp:

test_httpx.py:28: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../.pyenv/versions/3.7.9/envs/planet-client-python-3.7.9/lib/python3.7/site-packages/httpx/_client.py:1835: in __aenter__
    stream=True,
../../.pyenv/versions/3.7.9/envs/planet-client-python-3.7.9/lib/python3.7/site-packages/httpx/_client.py:1411: in send
    history=[],
../../.pyenv/versions/3.7.9/envs/planet-client-python-3.7.9/lib/python3.7/site-packages/httpx/_client.py:1448: in _send_handling_auth
    history=history,
../../.pyenv/versions/3.7.9/envs/planet-client-python-3.7.9/lib/python3.7/site-packages/httpx/_client.py:1476: in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
../../.pyenv/versions/3.7.9/envs/planet-client-python-3.7.9/lib/python3.7/site-packages/httpx/_client.py:1507: in _send_single_request
    ext={"timeout": timeout.as_dict()},
../../.pyenv/versions/3.7.9/envs/planet-client-python-3.7.9/lib/python3.7/site-packages/respx/mocks.py:137: in amock
    response = cls._send(request, instance=self, target_spec=spec, **kwargs)
../../.pyenv/versions/3.7.9/envs/planet-client-python-3.7.9/lib/python3.7/site-packages/respx/mocks.py:155: in _send
    httpx_response = cls.handler(httpx_request)
../../.pyenv/versions/3.7.9/envs/planet-client-python-3.7.9/lib/python3.7/site-packages/respx/mocks.py:86: in handler
    httpx_response = router.handler(httpx_request)
../../.pyenv/versions/3.7.9/envs/planet-client-python-3.7.9/lib/python3.7/site-packages/respx/router.py:270: in handler
    response = self.resolve(request)
../../.pyenv/versions/3.7.9/envs/planet-client-python-3.7.9/lib/python3.7/site-packages/respx/router.py:243: in resolve
    route, mock = self.match(request)
../../.pyenv/versions/3.7.9/envs/planet-client-python-3.7.9/lib/python3.7/site-packages/respx/router.py:231: in match
    response = prospect.match(request)
../../.pyenv/versions/3.7.9/envs/planet-client-python-3.7.9/lib/python3.7/site-packages/respx/models.py:394: in match
    result = self.resolve(request, **context)
../../.pyenv/versions/3.7.9/envs/planet-client-python-3.7.9/lib/python3.7/site-packages/respx/models.py:370: in resolve
    result = clone_response(result, request)
../../.pyenv/versions/3.7.9/envs/planet-client-python-3.7.9/lib/python3.7/site-packages/respx/models.py:62: in clone_response
    response.read()
../../.pyenv/versions/3.7.9/envs/planet-client-python-3.7.9/lib/python3.7/site-packages/httpx/_models.py:1162: in read
    self._content = b"".join(self.iter_bytes())
../../.pyenv/versions/3.7.9/envs/planet-client-python-3.7.9/lib/python3.7/site-packages/httpx/_models.py:1175: in iter_bytes
    for chunk in self.iter_raw():
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Response [200 OK]>

    def iter_raw(self) -> typing.Iterator[bytes]:
        """
        A byte-iterator over the raw response content.
        """
        if self.is_stream_consumed:
            raise StreamConsumed()
        if self.is_closed:
            raise ResponseClosed()
        if not isinstance(self.stream, typing.Iterable):
>           raise RuntimeError("Attempted to call a sync iterator on an async stream.")
E           RuntimeError: Attempted to call a sync iterator on an async stream.

../../.pyenv/versions/3.7.9/envs/planet-client-python-3.7.9/lib/python3.7/site-packages/httpx/_models.py:1209: RuntimeError

```

**Comment by lundberg** [comment]
The error is raised by HTTPX and nothing that RESPX can solve. I think it's by design that `httpx.Response` does not support to be instantiated with an async stream.

Do your mocked stream data really need to be async? I mean, the httpx client stream api should still work even if your given `_stream_img` is sync, allowing your tested logic to still work properly.

**Comment by jreiberkyle** [comment]
The issue is actually caused in `respx.models.clone_response` calling `response.read()` when the stream is an `AsyncIterator`. For an async stream, `response.aread()` should be called. I've tried adjusting `clone_response()` to fix this, but it is causing some async tests to fail so I'm not there yet...

```
from typing import AsyncIterable

def clone_response(response: httpx.Response, request: httpx.Request) -> httpx.Response:
    """
    Clones a httpx Response for given request.
    """
    response = httpx.Response(
        response.status_code,
        headers=response.headers,
        stream=response.stream,
        request=request,
        ext=dict(response.ext),
    )
    if isinstance(response.stream, AsyncIterable):
        response.aread()
    else:
        response.read()
    return response
```

**Comment by jreiberkyle** [comment]
Well, this doesn't really address the root problem, but if I bypass `clone_response()` , I'm able to run my test successfully. I do this by setting the optional `requests` parameter in `httpx.Response()` to any non-`None` value so [`respx.Route.resolve()`](https://github.com/lundberg/respx/blob/master/respx/router.py#L238) doesn't try to clone the response.

test_httpx.py
```
import httpx
import pytest
import respx


@respx.mock
@pytest.mark.asyncio
async def test_async_stream(tmpdir):
    dl_url = 'http://MockNotRealURL/download/?token=IAmAToken'

    img_headers = {
        'Content-Type': 'image/tiff',
        'Content-Length': '6',
        'Content-Disposition': 'attachment; filename="img.tif"'
    }

    async def _stream_img():
        yield b'bld'
        yield b'dce'

    # changed to add requests arg
    mock_resp = httpx.Response(200, stream=_stream_img(), headers=img_headers, request='donotcloneme')
    respx.get(dl_url).return_value = mock_resp

    filename = tmpdir / 'img.tif'

    async with httpx.AsyncClient() as cl:
        async with cl.stream('GET', dl_url) as resp:
            with open(filename, 'wb') as fp:
                async for chunk in resp.aiter_bytes():
                    fp.write(chunk)
```

**Comment by lundberg** [comment]
> The issue is actually caused in respx.models.clone_response calling response.read() when the stream is an AsyncIterator. For an async stream, response.aread() should be called.

This is true, but I'll try to explain and give some background...

The `httpx.Response` can be [instantiated](https://github.com/encode/httpx/blob/0f280af8b170ed5cc48c12a894f71a8b5762f748/httpx/_models.py#L927-L948) either by supplying a `stream` _(like your mock)_ or by passing `content`, `text`, `html` or `json` which in turn internally encodes into a sync stream by httpx.

To not mutate mocked responses and make test cases isolated, `clone_response` is needed. Here we re-instantiate the response using `stream` to completely replicate the mocked response regardless of how it was created (stream, text, json etc).

> Ultimately, looking into clone_response(), it looks like it is calling response.read() to populate response.content. I've tried adjusting clone_response() to populate response.content directly, but it is causing some tests to fail so I'm not there yet...

Correct, we call `response.read()` to populate "content" without accessing "private" response properties or utils.

In your adjusted `clone_response` you're passing both `stream` and `content`. If you look [here](https://github.com/encode/httpx/blob/0f280af8b170ed5cc48c12a894f71a8b5762f748/httpx/_models.py#L939) in `httpx.Response`, content is not respected when stream is passed.

To manually populate content and sidestep this, you'll have to set the "private" `response._content`, since `response.content` is a `@property`. This is not something I suggest though. We should try to not use "private" stuff in httpx likelier to change in future httpx versions that could lead to RESPX breaking.

So, I agree that `response.read()` is unfortunate since it breaks usage of async streams. We could maybe check the type of `stream` and only call `read()` if it is sync? Not sure if this is enough to fix this issue since content is not pre-populated?

**Comment by lundberg** [comment]
@jreiberkyle I've opened a PR that skips the `response.read()` for async response streams, could you please try the PR and see if it solves your issue/tests?

**Comment by jreiberkyle** [comment]
@lundberg that fixes it!
