### ISSUE TITLE
VCR-like functionality?

### ISSUE THREAD

**Issue by StephenBrown2** [lundberg/respx#16]
Thank you for this project!

I realize this may be out of scope, but do you think adding the ability to record and replay requests from YAML files is reasonable? Similar to [vcrpy](https://github.com/kevin1024/vcrpy/), but for httpx?

**Comment by lundberg** [comment]
Thanks, and yes, I think it's a bit out of scope, but it would definitely be possible to at least use `respx` to capture/record the requests made by `httpx`.

In your usecase, does the actual httpx-requested responses need to be mocked responses, or should the pass-through to to real endpoint?

Currently respx could be used by start mocking with `respx.mock` or `respx.start()` and then once all requests are done, fetch the result in `respx.calls`.

Something like...
```py
with respx.mock():
    httpx.get(...)
    httpx.get(...)
    ...
    print([request.url for request, response in respx.calls])
```

**Comment by StephenBrown2** [comment]
Understood. Yes, that would be necessary, and then I could build up the yaml from the processed calls and create my own fixture that loaded the files for replay.

**Comment by lundberg** [comment]
Yep, that would do it. Opened #17 for the pass-through feature.
