### ISSUE TITLE
Overlapping pattern/lookup combinations

### ISSUE THREAD

**Issue by flaeppe** [lundberg/respx#179]
I quite recently ran in to a typo which `respx` doesn't pick up on. It's probably not really `respx`s responsibility but thought perhaps it could deserve a warning? Or even better if it'd raise an error.

```python
import httpx
import respx
mocker = respx.mock(base_url="http://some.where/", assert_all_called=False)
mocker.post(method__in=("GET", "PUT"), path="/here/")
with mocker:
    httpx.post("http://some.where/here/", json={"la": "la"})
```

__Raises:__

```
respx.models.AllMockedAssertionError: RESPX: <Request('POST', 'http://some.where/here/')> not mocked!
```
Choosing any of the methods `POST`, `GET` or `PUT`. The same error is raised since there's really nothing that could possibly match more than 1 method.

This is the constraint on the route:
```
<Route <Scheme eq 'http'> AND <Host eq 'some.where'> AND <Method eq 'POST'> AND <Method in ('GET', 'PUT')> AND <Path eq '/here/'>>
```

**Comment by lundberg** [comment]
Good catch @flaeppe, thanks!

This seems to be caused by the *http method helper API", i.e. the `.post(...)` adds the `method` pattern, and "collides" with the predefined route that also has a `method__in` pattern.

IMO a warning would be enough, fired by the helper API. Let's start with that and maybe bump that to an exception in the future.

**Comment by lundberg** [comment]
I changed my mind 😉, it makes more sense to raise `TypeError` in this case.

Calling `.post("https://foo.bar/", url="https://example.org/")` would already fire a TypeError by python, due to the argument name colliding. So validating the lookups and fail likewise aligns better.

**Comment by flaeppe** [comment]
Nice! Sounds good
