### ISSUE TITLE
JSON path traversing raises exception rather than not using the route

### ISSUE THREAD

**Issue by dariobauer** [lundberg/respx#182]
Thanks for developing and documenting repsx, it is extremely useful.

One such useful features is the json pattern path traversing.
However I am having an issue that if I don't have a matching pattern before one where I use path traversing I get an error if my request has json but not that key.

```python
#conftest.py
@pytest.fixture(scope="module")
def mock_auth_api():
    with respx.mock(base_url="https://login.example.com/") as respx_mock:
        example_route = respx_mock.post(
            path__regex=r"([0-9a-zA-Z-]+)/oauth2/token$",
            json__grant_type="refresh_token",
        ).mock(side_effect=my_side_effect)
        yield respx_mock

#example_test.py
request_url = "https://app.diffhost.net/items/hFj8G5/endpoint"
headers = {"Accept": "*/*", "Authorization": "Bearer 123" }
json = {"type": "example"}
response = httpx.post(request_url, headers=headers, json=body)
```

Result:

```console
self = <JSON eq '"refresh_token"'>, request = <Request('POST', 'https://app.diffhost.net/items/hFj8G5/endpoint')>

    def parse(self, request: httpx.Request) -> str:
        content = super().parse(request)
        try:
            json = jsonlib.loads(content.decode("utf-8"))
        except JSONDecodeError:
            return ""
    
        if self.path:
            value = json
            for bit in self.path.split("__"):
                key = int(bit) if bit.isdigit() else bit
                try:
                    value = value[key]
                except KeyError as e:
>                   raise KeyError(f"{self.path!r} not in {json!r}") from e
E                   KeyError: "'grant_type' not in {'type': 'example'}"
```

**Expected:**

I would expect the KeyError to result in a non-match pattern, not an exception being raised.

Additionally it seems odd to me that since the base_url and path both do not match that the rest of the pattern is even checked. I presume using `pattern = M(path...) & M(json...)` would not change this?

**Comment by lundberg** [comment]
Thanks for reporting this issue @dariobauer!

> I would expect the KeyError to result in a non-match pattern, not an exception being raised.

Totally agree here, it feels more natural that this `KeyError` is silenced and failing the match instead 👍 

> Additionally it seems odd to me that since the base_url and path both do not match that the rest of the pattern is even checked. 

Also a good point, it would at least enhance the performance/speed if a failed pattern could omit the preceding pattern matching of a route.

> I presume using pattern = M(path...) & M(json...) would not change this?

Correct, that wouldn't change anything, e.g. `M(path=...)` is just a shortcut to `Path(...)` and the `AND` operator.

**Comment by dariobauer** [comment]
Thanks for your prompt response and these prs, much appreciated.
