### ISSUE TITLE
Raise on non-matching request

### ISSUE THREAD

**Issue by lundberg** [lundberg/respx#19]
Add setting to raise an exception when a request is captured but not matching any added pattern, with the possibility to disable/enable the feature.

Decide what the default behaviour should be, raise or always mock responses.

What exception should be raised, `AssertionError` or `ConnectionError`?

**Idea**:
```py
with respx.HTTPXMock(assert_all_mocked=False):
    respx.get("https://foo/bar/")
    httpx.get("https://ham/spam/")  # Would raise an AssertionError("non-matching")
```

**Comment by StephenBrown2** [comment]
The `responses` library uses requests' `ConnectionError`: https://github.com/getsentry/responses/blob/c5bc3e84ab6863c47dac891ca5daf341aed48d5a/responses.py#L595-L609

with the message `f"Connection refused by RespX: {request.method} {request.url} doesn't match RespX Mock"`

However, `httpx` doesn't have a `ConnectionError`, so perhaps an `InvalidURL` exception, or make your own `ConnectionError` as a subclass of httpx's `HTTPError`.

As to what should be the default, I think that mocking by default should be expected, as while I'm writing my tests I want to be made aware of when there's a call I should be mocking. IMO all calls should be mocked in unit tests, and passthrough should be the exception.

**Comment by lundberg** [comment]
> The `responses` library uses requests' `ConnectionError`: https://github.com/getsentry/responses/blob/c5bc3e84ab6863c47dac891ca5daf341aed48d5a/responses.py#L595-L609

If we raise an connection-related exception, I think it would be miss-leading the cause since when actually mocking a response one can intentionally raise similar exception to test some error handling in the tested code, `respx.get(..., content=httpx.HTTPError())`

I'm leaning towards an AssertionError to not trigger any unintended logic in the code being tested.

> As to what should be the default, I think that mocking by default should be expected

Agree @StephenBrown2, responses should always be mocked, if not marked for pass-through, and I think by default, one needs to opt-out from the assertion-check of request url matches an added pattern with a mocked response.
