### ISSUE TITLE
Cannot create a lookup to match empty params

### ISSUE THREAD

**Issue by MaxKh** [lundberg/respx#205]
https://github.com/lundberg/respx/blob/c76f632690cdfb2c878fe8fea999df0a26083eb3/respx/patterns.py#L502-L507

E.g. `respx_mock.get("https://example.com", params__eq={}).mock(...)` matches request with any query params including empty.
Looks like the value check must be more accurate.

respx version 0.19.2

**Comment by lundberg** [comment]
Interesting, thanks for reporting @MaxKh .

This part of the params pattern code needs to be tested with your empty params dict case:

https://github.com/lundberg/respx/blob/019a8a839193af265b15c92a2b7f8dec67c6cb65/respx/patterns.py#L266-L269

**Comment by lundberg** [comment]
Finally had time to look at this, and you were right @MaxKh, the issue was the too loose value check resulting in a `continue`.

Should be fixed and merged soon.
