### ISSUE TITLE
Tests failing with pytest-asyncio>=0.19.0

### ISSUE THREAD

**Issue by mweinelt** [lundberg/respx#207]
With pytest-asyncio==0.19.0 the asyncio-mode has been defaulted to strict. This breaks most of respx's tests.

https://github.com/pytest-dev/pytest-asyncio#modes

**Comment by lundberg** [comment]
Thanks, will look into this 👍

**Comment by lundberg** [comment]
Forgot that I already fixed this in #201 😂 , just not released yet.

**Comment by s-t-e-v-e-n-k** [comment]
#201 does not fix this issue, however `pytest --asyncio-mode=auto` is a workaround.

**Comment by lundberg** [comment]
You're right @s-t-e-v-e-n-k , I'll soon have a PR up changing this to `auto`

... will probably drop the unnecessary markers at the same time.
