### ISSUE TITLE
ResponseNotRead when attempting to access response data through respx.calls

### ISSUE THREAD

**Issue by StephenBrown2** [lundberg/respx#22]
I'm working on mocking an api client I've written using httpx which manipulates the data before returning it, and I can't seem to get the raw content from the request (before the manipulation). I've reconstructed what the client does, with cookies, headers, etc, to demonstrate the issue still happens with httpbin.org.

As you can see, the `request.content` is read (it's none, so an empty byte-string is expected), but the response is readable from httpx, but not respx.

Due to the api client construction, I don't immediately have access to the raw request (i.e. `httpx.get(...)` or `client.get(...)`), and I was hoping the mock would store the content in a retrievable format when passing through.

Note: Although not demonstrated here, this also happens with `text` and `json()`.

Am I doing something wrong or are my expectations misplaced?

Versions:
- respx (07ca910)
- httpx (0.7.6)

Demo:
```py
class TestGetContent:
    @respx.mock
    def test_get_content(self, mc_client):
        respx.get("https://httpbin.org/json", pass_through=True)
        base_url = httpx.URL("https://httpbin.org")
        cookies = httpx.Cookies()
        cookies.set(
            name="a_cookie", value="value", domain="httpbin.org",
        )
        headers = httpx.Headers(
            {"User-Agent": "my-python-client/0.0.7.dev0", "X-Auth": "auth_value"}
        )
        timeout = httpx.config.TimeoutConfig(timeout=300)
        c = httpx.Client(base_url=base_url, cookies=cookies, headers=headers, timeout=timeout)
        response = c.get("json")
        print(f"response.text={response.text}\n===")
        print(f"response.json()={response.json()}\n===")
        print(f"response.content={response.content}\n===")
        for req, resp in respx.calls:
            print(f"respx request.content={req.content}\n---")
            print(f"respx response.content={resp.content}\n---")
```

PyTest Result:
```py
>           print(f"respx response.content={resp.content}\n---")

tests/test_content.py:58: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Response [200 OK]>

    @property
    def content(self) -> bytes:
        if not hasattr(self, "_content"):
            if hasattr(self, "_raw_content"):
                raw_content = self._raw_content  # type: ignore
                content = self.decoder.decode(raw_content)
                content += self.decoder.flush()
                self._content = content
            else:
>               raise ResponseNotRead()
E               httpx.exceptions.ResponseNotRead

../../../Library/Caches/pypoetry/virtualenvs/test-py3.7/lib/python3.7/site-packages/httpx/models.py:816: ResponseNotRead
--------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------
response.text={
  "slideshow": {
    "author": "Yours Truly", 
    "date": "date of publication", 
    "slides": [
      {
        "title": "Wake up to WonderWidgets!", 
        "type": "all"
      }, 
      {
        "items": [
          "Why <em>WonderWidgets</em> are great", 
          "Who <em>buys</em> WonderWidgets"
        ], 
        "title": "Overview", 
        "type": "all"
      }
    ], 
    "title": "Sample Slide Show"
  }
}

===
response.json()={'slideshow': {'author': 'Yours Truly', 'date': 'date of publication', 'slides': [{'title': 'Wake up to WonderWidgets!', 'type': 'all'}, {'items': ['Why <em>WonderWidgets</em> are great', 'Who <em>buys</em> WonderWidgets'], 'title': 'Overview', 'type': 'all'}], 'title': 'Sample Slide Show'}}
===
response.content=b'{\n  "slideshow": {\n    "author": "Yours Truly", \n    "date": "date of publication", \n    "slides": [\n      {\n        "title": "Wake up to WonderWidgets!", \n        "type": "all"\n      }, \n      {\n        "items": [\n          "Why <em>WonderWidgets</em> are great", \n          "Who <em>buys</em> WonderWidgets"\n        ], \n        "title": "Overview", \n        "type": "all"\n      }\n    ], \n    "title": "Sample Slide Show"\n  }\n}\n'
===
respx request.content=b''
---
```

**Comment by lundberg** [comment]
Seems like the last *print* is missing, could you include the printed output of `print(f"respx response.content={resp.content}\n---")`, i.e. the response of the call.

Just to clarify, the `(request, response)` tuples in `respx.calls` are the actual `AsyncRequest` and `AsyncResponse` instances from `httpx`, regardless if mocked response details or pass-through.

The request in `respx.calls` is the one being sent, *in your case pass-through*. And since it's a `GET` request, I guess the content/body should be empty.

The response in `respx.calls` should be the exact same instance as the response from your line `response = c.get("json")`, i.e. `respx.calls[-1][1].json()` is the response content of the pass-through request.

**Comment by StephenBrown2** [comment]
> Seems like the last print is missing, could you include the printed output of
print(f"respx response.content={resp.content}\n---"), i.e. the response of the call.

That's where the issue happens, it doesn't print because of the error accessing `resp.content`. Splitting out the prints gives the same:
```py
        for req, resp in respx.calls:
            print(f"respx request.content=")
            print(f"{req.content}")
            print("---")
            print(f"respx response.content=")
            print(f"{resp.content}")
            print("---")
```
```py
...snip...
===
respx request.content=
b''
---
respx response.content=
<END>
```

> The response in respx.calls should be the exact same instance as the response from your line response = c.get("json"), i.e. respx.calls[-1][1].json() is the response content of the pass-through request.

That was my assumption. I had suspected they should be the same, based on a brief code dive, but an assertion says they aren't identical (maybe the same but cloned?)
```py
>       assert response == respx.calls[-1][1]
E       assert <Response [200 OK]> == <Response [200 OK]>

tests/test_content.py:56: AssertionError
```

`respx.calls[-1][1].content` again results in an `ResponseNotRead` exception.

So I'm not sure why, aside from the contents being a stream, since it gets read once already in the call, but I think httpx doesn't currently allow for rewinding that?

**Comment by lundberg** [comment]
> That's where the issue happens, it doesn't print because of the error accessing `resp.content`. Splitting out the prints gives the same:

Ah, my bad, misunderstood.

> That was my assumption. I had suspected they should be the same, based on a brief code dive, but an assertion says they aren't identical (maybe the same but cloned?)

I'll reproduce the issue and investigate. Appreciate your help and input, please continue digging ;-)

> So I'm not sure why, aside from the contents being a stream, since it gets read once already in the call, but I think httpx doesn't currently allow for rewinding that?

Good input.

**Comment by StephenBrown2** [comment]
Sure thing. Interestingly, I can call `response.content` (from `httpx`) multiple times in the test, but not `resp.content` (from `respx`).

**Comment by StephenBrown2** [comment]
Just further reproduction, here's the absolute minimum reproduction case:
```py
class TestGetContent:
    @respx.mock
    def test_get_content(self):
        respx.get("https://httpbin.org/json", pass_through=True)
        response = httpx.get("https://httpbin.org/json")
        respx.calls[-1][1].text # or .json(), or .content, raise ResponseNotRead
		assert response.text == respx.calls[-1][1].text
```
Also happens without `pass_through`:
```
class TestGetContent:
    @respx.mock
    def test_get_content(self):
        respx.get("https://httpbin.org/json")
        response = httpx.get("https://httpbin.org/json")
        assert response.text == respx.calls[-1][1].text
```
Or when setting `content=`... actually seems to happen no matter what options I pass to `respx.request(...)`

**Comment by lundberg** [comment]
I've finally found the cause of this issue. RESPX patches `BaseClient._get_response` which both sync and async clients use. Problem is that in that stage the response is still async due to internal dispatch logic in `HTTPX`. The PR #23 should now solve this, by patching earlier individually in *sync* and *async* clients.

Thanks for raising this issue @StephenBrown2 ! Please try the PR in your use case, before I merge.

**Comment by StephenBrown2** [comment]
Yup, looks like it does! Thanks for the quick work on that.
