### ISSUE TITLE
Empty query params in httpx 0.23.1

### ISSUE THREAD

**Issue by g-as** [lundberg/respx#222]
https://github.com/encode/httpx/pull/2354

Empty query param is now kept:
```python
def test_empty_query_params():
    q = httpx.QueryParams({"a": ""})
    assert str(q) == "a="

    q = httpx.QueryParams("a=")
    assert str(q) == "a="

    q = httpx.QueryParams("a")
    assert str(q) == "a="
```

which breaks at least one test:
```python
@pytest.mark.parametrize(
    ("lookup", "params", "url", "expected"),
    [
        ...
        (Lookup.CONTAINS, "x=", "https://foo.bar/?x=1", True),  # query, not params
        ...
    ],
)
def test_params_pattern(lookup, params, url, expected):
    request = httpx.Request("GET", url)
    assert bool(Params(params, lookup=lookup).match(request)) is expected
```

**Comment by lundberg** [comment]
Not sure if we should keep that test, i.e. keep support and allow matching `?x=1` _contains_ `?x=` 🤔 ?

We already have the support for `ANY` when using params map, e.g. `params={"x": ANY}`.

Maybe better to be strict and say `x=` != `x=1`.

**Comment by g-as** [comment]
Agreed.

Either drop the test case, or set the expected result to `False`.

**Comment by g-as** [comment]
But dropping it ensures tests pass for all httpx versions if you don't want to add a version constraint on `httpx`.

**Comment by lundberg** [comment]
> Either drop the test case, or set the expected result to False.

Yeah, I'd say flipping the expected test result to `False` is best.

> But dropping it ensures tests pass for all httpx versions if you don't want to add a version constraint on `httpx`.

I think it's fine leaving it even though the test suite breaks on this particular test-case on an old httpx version, I mean that specific contains-match is an undocumented feature.

**Comment by g-as** [comment]
All good!
