### ISSUE TITLE
Drop `assert_all_called` from `Router`

### ISSUE THREAD

**Issue by lundberg** [lundberg/respx#233]
The _base_ `Router` makes no use of the `assert_all_called` kwarg.

It should therefor be dropped from `Router`, but kept and only usable in the _main_ `MockRouter`.

Also extend [Router](https://lundberg.github.io/respx/guide/#mock-without-patching-httpx) documentation with an example on how to assert that all routes was called.

**Comment by morenoh149** [comment]
I'd like to address this issue. Is it just removing this kwarg? https://github.com/lundberg/respx/blob/master/respx/router.py#L43

Also should this project have a CONTRIBUTING.md?

**Comment by lundberg** [comment]
> I'd like to address this issue. Is it just removing this kwarg? https://github.com/lundberg/respx/blob/master/respx/router.py#L43

Yes, since it doesn't affect anything and is a *noop* when a plain `Router` is used. 

But to make it clear, the kwarg is kept [here](https://github.com/lundberg/respx/blob/b014780bde8e82a65fc6bb02d62b89747189565c/respx/router.py#L327) for the `MockRouter` used by `respx.mock(...)`. So, the *super* call need to be adjusted there as well, so that the *setting* is not lost for the mock router and its decorator/contextmanager features.

> Also should this project have a CONTRIBUTING.md?

Yeah, that's probably a good idea, e.g. I should describe how to run tests, linting etc 😉

**Comment by lundberg** [comment]
Revisiting this now and actually changed my mind @BeyondEvil 😂 

I think we should keep the `assert_all_called` kwarg/setting since my suggestion by manually calling it in #228 is a working solution.

I'll probably just update the docs and trying to mention this when using the `Router` manually without any context managers used.
