### ISSUE TITLE
Feature request: easily mock cookies

### ISSUE THREAD

**Issue by phha** [lundberg/respx#249]
It would be super nice if we could do something like this:

```python
respx.get("example.com").respond(cookies={"foo": "bar"})

cookies = httpx.Cookies()
respx.get("example.com").respond(cookies=cookies)
```

**Comment by lundberg** [comment]
Sounds like a reasonable feature .. we'll need to dig in httpx to figure out how to best construct a response with the cookies, e.g. `Set-Cookie` headers or other way

**Comment by phha** [comment]
I've followed the trail a bit and it seems like we'd have to set the headers.

`Response.cookies` is a read-only property

```python
@property
def cookies(self) -> "Cookies":
    if not hasattr(self, "_cookies"):
        self._cookies = Cookies()
        self._cookies.extract_cookies(self)
    return self._cookies
````

Where

```python
def extract_cookies(self, response: Response) -> None:
    """
    Loads any cookies based on the response `Set-Cookie` headers.
    """
```

Which leads to the question whether `headers=`  or `cookies=` should take precedence in case of collisions.

**Comment by lundberg** [comment]
@phha I finally got around and implemented a feature for this 😅. Please try the PR out locally, if possible, to rule out any bugs.
