### ISSUE TITLE
Show actuall request when umocked requests are made

### ISSUE THREAD

**Issue by dolfandringa** [lundberg/respx#250]
I have a unittest that uses respx through the pytest fixture to mock the http requests. I changed something in the code, and now a bunch of tests are failing with `respx.models.AllMockedAssertionError: RESPX: <Request('POST', 'https://our.partner.example.com/their/webhook')> not mocked!`. 

So far, hurray for unittests. But it doesn't show me what request was actually made. It would be great if there was some kind of output showing the mocked requests and the actual requests, so I can see the difference. Now  i am just guessing what the issue is. Pytest normally can show diffs on assertion errors with plain values.

**Comment by lundberg** [comment]
The "all mocked assertion" means that respx is active and configured to require every httpx request to match respx mock route, i.e. the request above (https://our.partner.example.com/their/webhook) does not match any route in your respx fixture instance.

Need more details/example, e.g. fixture some the unittest that fails

**Comment by lundberg** [comment]
Kind-of related to #244

**Comment by lundberg** [comment]
Need more context, closing this for now. Please re-open if still a problem and/or docs should be adjusted.

**Comment by dolfandringa** [comment]
I just ran into this again months later funnily enough. So the issue is that respx gives a very nice error if a url was requested but not mocked. 
Normally (with pytest), it shows the diff between the actual and expected values, which really helps with debugging.
With respx we only get an error that a specific url was not mocked, but it would be much easier to debug if there was some kind of diff showing all mocked and intercepted requests.

**Comment by dolfandringa** [comment]
An example would be:

```
def test_diff(respx_mock: respx.MockRouter):
    url1="https://test.com/foo"
    url2="https://test.com/bar"
    url3="https://test.com/baz"
    respx_mock.get(url1).mock()
    respx_mock.get(url2).mock()
    response=httpx.get(url1)
    response=httpx.get(url3)
```
In this case it would be nice to show an error like:
```
AllMockedAssertionError: RESPX: <Request('GET', 'https://test.com/baz')> not mocked!
Expected:   <Request('GET', 'https://test.com/foo')>, <Request('GET', 'https://test.com/bar')> 
                                                                                                                                                              ^         
Received:   <Request('GET', 'https://test.com/foo')>, <Request('GET', 'https://test.com/baz')> 
                                                                                                                                                              ^ 
```
