### ISSUE TITLE
Incompatibility with httpx 0.28.0

### ISSUE THREAD

**Issue by PriOliveira** [lundberg/respx#277]
When upgrading httpx from 0.27.2 to 0.28.0, the mocks that were previously correctly detected as mocked, stop being considered as so and raise an `AllMockedAssertionError`.

**Comment by PrieJos** [comment]
Hi All,

For some reasons I couldn't find out, the httpcore mocker (`respx.mocks.HTTPCoreMocker`) is not being able to patch the patterns for the mocked routes upon test function executions. 

A workaround that is working for me at least is to switch to the httpx mocker (`respx.mocks.HTTPXMocker`) when starting the mock router. That may look like something similar in your tests to this:

```python
# Build your mocked responses here
mocked_resp1 = ...
mocked_resp2 = ...
mocked_resp3 = ...

# Mocked API service
async with respx.mock(base_url=base_url_mock, using="httpx") as respx_mock:
    respx_mock.get("/", name="$service_document$").mock(mocked_resp1)
    respx_mock.get("/$metadata", name="$metadata$").mock(mocked_resp2)
    respx_mock.head("/", name="$csrf_token$").mock(mocked_resp3)
    yield respx_mock
```

The different is the argument `using="httpx"` when opening the context manager.

Cheers
Jose M. Prieto

**Comment by ndhansen** [comment]
Hey, I've raised a fix in #278, please let me know if that helps.

**Comment by tomchristie** [comment]
Ooof that's frustrating.

Does it make more sense for us to switch back to `str|bytes` on our side, or leave the fix?change? to your side?

**Comment by lundberg** [comment]
> Does it make more sense for us to switch back to str|bytes on our side, or leave the fix?change? to your side?

@tomchristie .. #278 solves this issue quite clean on our end, so I'll merge it as soon it's updated/linted and will push a new release asap
