### ISSUE TITLE
Is this project dead? No commits for nine months as of today.

### ISSUE THREAD

**Issue by JohnVillalovos** [lundberg/respx#279]
Just wondering if this project is dead.

I see that there is a show stopper issue with no responses from the maintainer: https://github.com/lundberg/respx/issues/277

**Comment by nejch** [comment]
Hi @lundberg! :wave: This project is listed as the recommended httpx mocking library in their docs (https://www.python-httpx.org/compatibility/#mocking), so it'd be great to see that continue. Not sure if you've moved on to other things though.

Have you considered using a dedicated namespace like https://github.com/respx/respx and adding a few other maintainers that you trust and could merge PRs (e.g. dependency updates and breaking changes like the one linked)?

Or maybe the encode folks would consider moving it somewhere to have multiple people involved @tomchristie? (sorry for the ping). The other active library is https://github.com/Colin-b/pytest_httpx, but also seems to have a single maintainer so it's potentially in a similar situation.

**Comment by nejch** [comment]
Ah it was just an idea, I don't think that's necessary.

Probably still the cleanest way then is to bring this up to date since this library is not pytest-specific and the community around it seems to be active enough to follow along httpx changes (and I guess things might stabilize with v1, not that they break often).

**Comment by stinovlas** [comment]
I believe that this projects checks most of the boxes for possible transfer to JazzBand. If @lundberg is no longer interested in maintaining this project (which is totally understandable), we could probably transfer it. Transferring rights to publish to PyPI would also be helpful.

Of course, there's always a possibility of forking the project (and creating new package name on PyPI), but I'd like to be sure that @lundberg no longer has any interest in it before I'd do that.

**Comment by lundberg** [comment]
Nope, project is not dead @JohnVillalovos 😅 .. just been so stable, i.e. no new features or releases for a while 😉

**Comment by lundberg** [comment]
@nejch I like the idea of adding more maintainers, great suggestion 👍

**Comment by lundberg** [comment]
@tomchristie I haven't had time to look into the issue #277 .. but hopefully it's possible to have a clean fix in respx without reverting in httpcore

**Comment by lundberg** [comment]
Let's continue discussion in #277 @JohnVillalovos

**Comment by JohnVillalovos** [comment]
> Nope, project is not dead @JohnVillalovos 😅 .. just been so stable, i.e. no new features or releases for a while 😉

Awesome! Glad to hear it is still alive. Thanks!
