### ISSUE TITLE
'Request' type annotation

### ISSUE THREAD

**Issue by chbndrhnns** [lundberg/respx#40]
With the snippet below (which is inspired from the examples), I get "Unresolved attribute reference 'called' for class 'Request' " in PyCharm on line 3. Would it be possible to expose a type that I can use for annotation that includes the `.called` property?

```python
@respx.mock
def test_something():
    request: Request = respx.get("https://foo.bar/", content="foobar")
    response = httpx.get("https://foo.bar/")
    assert request.called
    assert response.status_code == 200
    assert response.text == "foobar"
```

**Comment by StephenBrown2** [comment]
Respx actually returns a [`RequestPattern` object](https://github.com/lundberg/respx/blob/ec8d14ee4a810189e088a69c89723b493de8df43/respx/models.py#L131), which does implement [`.called`](https://github.com/lundberg/respx/blob/ec8d14ee4a810189e088a69c89723b493de8df43/respx/models.py#L158)

You can import it with `from respx.models import RequestPattern`, but personally I don't type my test bodies...

**Comment by chbndrhnns** [comment]
That solves it, I guess. Thanks for the super-quick response!
