### ISSUE TITLE
respx methods not available for auto-completion

### ISSUE THREAD

**Issue by chbndrhnns** [lundberg/respx#41]
When I have this snippet, I see the message `Cannot find reference 'post' in '__init__.py' ` in PyCharm.

```python
request: Request = respx.post(
        url=adapter.create_project_endpoint,
        status_code=201,
        content={
            'id': 123,
            'name': expected.name
        })
```

Would it be possible to expose the public API so that it's available for auto-completion?

**Comment by lundberg** [comment]
Thanks for raising this, will try to figure this one out. Would like to see a solution not duplicating the api.
