### ISSUE TITLE
Question: how to change content for request to same url

### ISSUE THREAD

**Issue by tax** [lundberg/respx#47]
First of all thanks for creating this package!

I read the documentation but I could not find an answer to this question but maybe I missed it.

My question is, if it is possible to change the content of a request within the same test so that the second request to the same url can return different content. Currently the second request also returns **'login error'** in this example:

```python
    @respx.mock
    def test_two_mocks(self) -> None:
        respx.post('https://192.168.0.69:3031/rest/login', content='login error', status_code=500)
        response = httpx.post("https://192.168.0.69:3031/rest/login")
        assert response.text == 'login error'

        # make second request with different conten
        respx.post('https://192.168.0.69:3031/rest/login', content='login failed', status_code=400)
        response = httpx.post("https://192.168.0.69:3031/rest/login")
        assert response.text == 'login failed'
```

**Comment by lundberg** [comment]
This should be possible. Try moving the second mock next to the first one.

```py
@respx.mock
    def test_two_mocks(self) -> None:
        respx.post('https://192.168.0.69:3031/rest/login', content='login error', status_code=500)
        respx.post('https://192.168.0.69:3031/rest/login', content='login failed', status_code=400)

        response = httpx.post("https://192.168.0.69:3031/rest/login")
        assert response.text == 'login error'

        response = httpx.post("https://192.168.0.69:3031/rest/login")
        assert response.text == 'login failed'
```

Further reading under [repeated patterns](https://lundberg.github.io/respx/api/#repeated-patterns) in the docs.

Please confirm that it worked, thanks.

**Comment by tax** [comment]
Works  perfect! thanks a lot

**Comment by mharrisb1** [comment]
This is the first thing that pops up on searches for how to do this. Is this outdated? I was not able to get this to work with v0.20.2.

Is [side effects](https://lundberg.github.io/respx/guide/#mock-with-a-side-effect) the preferred approach now?

**Comment by lundberg** [comment]
Yes @mharrisb1, an [iterable side effect](https://lundberg.github.io/respx/guide/#iterable) is what I'd suggest.

Alternatively you could utilize [named routes](https://lundberg.github.io/respx/guide/#named-routes) and re-mock the response later in the same test, e.g. 
```py
respx.post(..., name="some_name").respond(201)
...
respx.routes["some_name"].respond(200)
```
