### ISSUE TITLE
Asynctest owner suggests switch to asyncmock

### ISSUE THREAD

**Issue by chbndrhnns** [lundberg/respx#61]
When using the `asynctest` package (which is a dependency of `respx`) with Python 3.8+, there are deprecation warnings:

```
.venv/lib/python3.8/site-packages/asynctest/mock.py:448
  /Users/.../.venv/lib/python3.8/site-packages/asynctest/mock.py:448: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def wait_next(self, skip=0):
```

The author of asynctest suggests moving to `asyncmock` instead of resolving the issues ([1](https://github.com/Martiusweb/asynctest/issues/132), [2](https://github.com/Martiusweb/asynctest/pull/134)).

I am wondering if this would be an option for you to make `respx` future-proof.

**Comment by lundberg** [comment]
Thanks or raising this "issue".

I agree that we should use `asyncmock` for Python 3.8+. Easiest would be to move all `patch` imports to, lets say, a `compat` module that could dispatch which one to use depending on python version, `asynctest` or standard lib.

Any thoughts welcome!

**Comment by chbndrhnns** [comment]
I am not very experienced in supporting multiple python versions so I cannot offer lots of thoughts here. What you suggest sounds reasonable, though.  

I have not yet used asyncmock, either.

**Comment by hugovk** [comment]
In the meantime, to silence the warnings in pytest, you can add something like this to `pytest.ini`, but note it'll silence them in your own code too:

```ini
[pytest]
filterwarnings =
    # respx/asynctest: https://github.com/lundberg/respx/issues/61
    ignore:"@coroutine" decorator is deprecated since Python 3.8, use "async def" instead:DeprecationWarning
```

**Comment by lundberg** [comment]
I've opened #69 . Since we're only patching methods and not really using async magic mocks, I was able to drop the `asynctest` dependency completely.

**Comment by lundberg** [comment]
@chbndrhnns , @hugovk please try out the PR. Note that the release of this will remove the dep of `asynctest`, so if you use it elsewhere in your tests, the dep needs to be added separate.

**Comment by hugovk** [comment]
My unit tests are passing with the https://github.com/lundberg/respx/pull/69 branch 👍 

* https://github.com/hugovk/pypistats/pull/138 (ignore the "failure", it's a Codecov timeouts, and `3.8, ubuntu-18.04` is the RESPX build)

**Comment by lundberg** [comment]
Thanks for testing @hugovk , `0.12.0` now released.
