### ISSUE TITLE
httpx exceptions take request in __init__

### ISSUE THREAD

**Issue by frjonsen** [lundberg/respx#71]
In one of my tests, I am checking that we are handling connection timeouts correctly. To do this, I need a raise a `httpx.ConnectTimeout`.

[The documentation](https://lundberg.github.io/respx/api/#request-error) suggests simply instantiating it and passing it as content, but it appears that httpx recently made some changes to the exception hierarchy, and [at the bottom](https://github.com/encode/httpx/blob/master/httpx/_exceptions.py#L44) is now a HTTPError with an init-signature of `def __init__(self, message: str, *, request: "Request")`. `message` can probably just be whatever, but the `request` is trickier. Passing `None` seems to work, but I guess that's only because nothing internally in httpx attempts to read from it, for now. Since the parameter is not `Optional`, it should probably be dealt with sooner or later. If possible, it would be great to just pass the Exception-type to respx rather than passing an Exception instance, so that respx can fill in the request.

**Comment by lundberg** [comment]
Yes, this is true, HTTPX changed the exceptions recently and I needed to do the same for the `test_rasing_content` test, i.e. set request=None.

Your suggestion is a great solution, but maybe not so future-proof to assume that exception type and spec would take these args in all cases.

Though, this got me thinking of the exception mapping that HTTPX does under the hood. Low level exceptions from `httpcore` is already mapped against `httpx` exceptions. This means that if you instead pass a `httpcore.ConnectTimeout()`, httpx will re-raise that as a `httpx.ConnectTimeout` instance with the proper request!

I think this is the best way and RESPX docs should be changed to...

```py
import httpcore
import httpcore
import respx


@respx.mock
def test_something():
    respx.get("https://foo.bar/", content=httpcore.ConnectTimeout())
    response = httpx.get("https://foo.bar/")  # Will raise
```

...agree @frjonsen ?

**Comment by lundberg** [comment]
Docs updated with `httpcore.ConnectTimeout`
