### ISSUE TITLE
Text encoding is changed when passing a utf-8 string to content

### ISSUE THREAD

**Issue by konstin** [lundberg/respx#73]
I'd expect that utf-8 characters (such as German umlauts) are returned the way I passed them to `content`, however this is not the case:

```python
import httpx
import respx

with respx.mock() as respx_mock:
    text_in = "Geh&#xE4;usegröße"
    respx_mock.get("https://example.com", content=text_in)
    text_out = httpx.get("https://example.com").text
    print(text_in)
    print(text_out)
    print(text_in == text_out)
```

```
Geh&#xE4;usegröße
Geh&#xE4;usegrÃ¶Ãe
False
```

Versions: respx 0.12.1 and httpx 0.14.3

**Comment by lundberg** [comment]
Interesting! Will investigate, thanks.

Debugging help appreciated ;-)

**Comment by lundberg** [comment]
I've now narrowed it down to the content type heder @konstin .

If you set the content type it should work. It would be nice though to default to `utf-8`.

I already had `TODO:`s both in a [test](https://github.com/lundberg/respx/blob/master/tests/test_api.py#L163) and [content handling](https://github.com/lundberg/respx/blob/master/respx/models.py#L189), mentioning this "problem" ;-)

Here's your example, modified, that should work:
```py
import httpx
import respx

with respx.mock() as respx_mock:
    text_in = "Geh&#xE4;usegröße"
    respx_mock.get("https://example.com", content=text_in, content_type="text/plain; charset=utf-8")
    text_out = httpx.get("https://example.com").text                                 #  ^
    print(text_in)
    print(text_out)
    print(text_in == text_out)
```

I need to dig into HTTPX to see how it's solved there, *default-wise*. Happy to see input or feedback how to best solve this.

**Comment by lundberg** [comment]
Worth mentioning, RESPX [sets a default](https://github.com/lundberg/respx/blob/master/respx/models.py#L151-L152) `Content-Type` header, if not specified.

This might be the problem *or* the place to fix this issue.

When I change this default header to `text/plain; charset=utf-8`, a test with your input `"Geh&#xE4;usegröße"` works without specifying `content_type` when mocking @konstin .

But, if I remove setting the default content type header completely, your test input still works, but unfortunately fails the existing [test input](https://github.com/lundberg/respx/blob/master/tests/test_api.py#L158) `"äpple"`.

**Comment by konstin** [comment]
Thank you for investigating, setting `text/plain; charset=utf-8` works!

I'd although like a `utf-8` default; If I understand the new docs correctly, https://github.com/encode/httpx/pull/1269 might solve this without any extra work.

**Comment by lundberg** [comment]
Awesome if this could be solved in HTTPX!

If/when that HTTPX PR is merged, we'll need to decide if it's enough to just remove mentioned RESPX todo's and the encoding-code with it.

**Comment by lundberg** [comment]
Update...

With HTTPX `0.15.0` and recent RESPX alignments in `master` to httpcore `0.11.0`, this seems to work now without specifying charset or content type @konstin !

I've extended the content test with your example in #78 to clarify.

Still not sure what to do with our default [Content-Type header](https://github.com/lundberg/respx/blob/master/respx/models.py#L148-L149), or the hard utf-8 [content encoding](https://github.com/lundberg/respx/blob/master/respx/models.py#L186) in the response template.

**Comment by lundberg** [comment]
About the content encoding, I think we should introduce `encoding` option to `ResponseTemplate` to align with HTTPX response flexibility.

From [HTTPX chardet PR](https://github.com/encode/httpx/pull/1269):
> *Users can override this behaviour if required with an explicit `response.encoding = ...`

We can have it set to `utf-8` by default, but overridable when adding patterns to RESPX.
