### ISSUE TITLE
Using stub files to satisfy editors

### ISSUE THREAD

**Issue by jocke-l** [lundberg/respx#75]
As explained in #74 the public API was intentionally made verbose to make editors aware of the typing. This is bad for maintenance.

The solution I've found so far is to use Python Stub Files (`.pyi`) for the public API (at least this works perfectly with PyCharm). The downside is that these stub files need to be maintained as well. They can however be automatically generated, so the maintenance cost should be minimal. I've searched for existing solutions and found that `mypy` includes a CLI-tool called `stubgen` which at first glance seem to do exactly what we want. The problem is that this tool seem to be equally stupid to some editors, that is, it can't infer the types, so it just says `Any`.

I am willing to write a tool (or contribute to `stubgen`) to automatically generate these stub files. But before I start I would like to hear your opinion about this. Is it worth it or not?

**Comment by SlavaSkvortsov** [comment]
I don't understand why do you want to use Stub Files, when you can just annotate the existing code. As far as I know, stub files are useful if you are trying to support Python < 3.5. 

Mypy will validate in-code type annotation, it will be easy to maintain the code, and autocomplete + hints from IDE will work

**Comment by jocke-l** [comment]
@SlavaSkvortsov Yes I know that. Stub files were introduced in PEP-484 to deal with untyped code, such as those parts of Pythons standard libarary that is written C. Because Python is fundamentally a dynamically typed language, with opt-in support for static typing, the static analyzers cannot give you the same guarantees that they would in other languages. For example:

```python
def spam(foo: str, bar: int) -> int:
   ...


eggs = functools.partial(spam, "lots of spam")  # What is the type of `spam`? Callable[[int], int] of course!
```

Static analyzers can't handle this at all, because they're... well, static, and partial application in python is a runtime thing.

By complementing the above code with this stub file the type can be resolved statically:

```python

def eggs(bar: int) -> int:
    ....
```

The same thing coud be achieved without stub files by simply:

```python
def spam(foo: bool, bar, int) -> int:
   ...

def eggs(bar: int) -> int:
   return spam("lots of spam", bar)
```

This is not optimal in all cases. For example [here](https://github.com/lundberg/respx/blob/master/respx/api.py#L57-L296) and [here](https://github.com/lundberg/respx/blob/master/respx/transports.py#L140-L348). All that means a simple parameter addition will need changes in 31 different places compared to just one.

Now most of that boiler plate would be moved to stub files, however, they can pretty easily be auto-generated for our purpose. And that is what I'm suggesting.

**Comment by SlavaSkvortsov** [comment]
@jocke-l thanks for the response! 
Sorry, I still can't understand why do we need to use stub files in a library where we could apply types annotations? I totally understand when we need to annotate C code or it's smth complicated and will require a lot of hours to annotate it (like Django). But here we have a small lib and it could be easily annotated. 

For example, here you can write smth like this
```python 
eggs: Callable[[int], int] = functools.partial(spam, "lots of spam")
```
and Mypy will be able to handle it.

> All that means a simple parameter addition will need changes in 31(!) different places compared to just one.

Yes, but when I, as a user of this lib open the source to check what I'm doing wrong, I'll see correct type annotations.

**Comment by jocke-l** [comment]
@SlavaSkvortsov

> For example, here you can write smth like this
> 
> ```python
> eggs: Callable[[int], int] = functools.partial(spam, "lots of spam")
> ```

This defeats the purpose of using `partial` in the first place. In addition to that, it didn't work in PyCharm last time I tried.

> Yes, but when I, as a user of this lib open the source to check what I'm doing wrong, I'll see correct type annotations.

This also applies to stub files.

Anyway, I'm not sure this is as big of on issue anymore since the recent rework of the public API.

@lundberg Maybe it's time to close this issue?

**Comment by lundberg** [comment]
Agree, lets close this one now that the api is simpler and less repetitive.

Lovely python discussion, though!
