### ISSUE TITLE
Enhancement proposal: Increase flexibility of method in MockTransport().add?

### ISSUE THREAD

**Issue by lbillinghamtn** [lundberg/respx#76]
Thank you for a very useful tool.

Would you be interested in allowing more flexibility in the method parameter to `MockTransport().add`: 
so e.g. it can be called with "get" as well as "GET" ?

Roughly equivalent to making the following test pass

```python
@pytest.mark.asyncio
@pytest.mark.parametrize(
    "method",
    ["GET", "get", respx.get,],
)
async def test_can_add_by_lowercase_or_api_func_method(client, method):
    url = "https://example.org/"
    content = {"spam": "lots", "ham": "no, only spam"}
    async with MockTransport() as respx_mock:
        request = respx_mock.add(method, url, content=content)
        response = await client.get(url)
        assert request.called is True
        assert response.json() == content
``` 

### Background

I was converting from responses to `respx` and at some point had this 

```python
with respx.MockTransport() as httpx_mock:
        respx_context.add(responses.GET, ... )
```
which unexpectedly worked. But then I confused trying to calque with `responses.get` -> `respx.get`, then with `respx_context.add("get, ... )`.

If you are interested, I could put a PR together.

**Comment by lundberg** [comment]
In your examples, you use `respx.add` which can be seen as equivalent to `responses.add`.

On top of `add`, RESPX also has the [HTTP method shorthands](https://lundberg.github.io/respx/api/#http-method-api)  to align with the HTTPX api. To clarify, `respx.get` is not a http method string, it's `add` shorthand.

I'd recommend using `respx.get(url, content=content)` to make your tests more dry...

```py
with respx.mock:
    request = respx.post(url, content=content)
    response = await client.post(url)
```

It would be possible to support lowercase http method arg in the `add` api, but I think it's best to keep it uppercase like HTTPX does. OK @lbillinghamtn ?
