### ISSUE TITLE
Disable/enable mocking of real service.

### ISSUE THREAD

**Issue by max-iov42** [lundberg/respx#95]
I would like to be able to disable/enable mocking with `respx`so I could run my tests against the real system. I thought I could do that using `respx.stop()`. But calling `stop()` just raises an error like:

```python
self = <respx.mocks.MockTransport object at 0x7fb729b64460>, clear = True, reset = True

    def stop(self, clear: bool = True, reset: bool = True) -> None:
        """
        Unregister transport and stop patching, when no registered transports left.
        """
        try:
            if self._assert_all_called:
                self.assert_all_called()
        finally:
            if clear:
                self.clear()
            if reset:
                self.reset()
    
            # Unregister current transport
>           assert self in self.transports, "RESPX transport already stopped!"
E           AssertionError: RESPX transport already stopped
```
Maybe there is a simple way to do that - I just didn't find one it.

**Comment by lundberg** [comment]
Hmm, it could be that the transport is being stopped twice, once by you, and second by exiting context manager or decorator.

Please check your traceback and see if `stop` is being called via transport `__exit__`.

Just to clarify, does the stopping works so that the requests are being sent to your real system, but the assertion error mentioned gets fired.

**Comment by max-iov42** [comment]
As I said, maybe I use the start/stop feature in the wrong way because I do not understand the underlying details how the mocking is working. The code looks like
```python
def test_create_identity_content(
    client: Client,
    mocked_requests_200: respx.MockTransport,
) -> None:
    """It sends the request body to create an identity as expected."""
    respx.stop()
    # Setup is done with pytest.fixtures
    # SUT action
    _ = client.put(
        Identity,
        request_id="e9c79db4-2b8b-439f-95f5-7574005458ef",
    )
    # Here come some assertions
```
I thought I could just use `stop()` in a test and it would send he request to the real service.

The stack trace for this call above looks like:
```
def test_create_identity_content(
    client: Client,
    mocked_requests_200: respx.MockTransport,
) -> None:
    """It sends the request body to create an identity as expected."""
    respx.stop()  # TODO this should be controlled with a pytest.maker.
    _ = client.put(
        Identity,
        request_id="e9c79db4-2b8b-439f-95f5-7574005458ef",
    )
```

What I would like to do is to define a `pytest` marker which I would use to control if the request is sent to the service or if it is mocked. How do you would suggest I do that?

**Comment by lundberg** [comment]
Now I understand.

Since there can be multiple RESPX mock transports started, all needs to be stopped before httpx/httpcore is unpatched.

In your fixture you're instantiating a new mock transport and yielding it.

Try stopping that instance, instead of stopping the global `respx.mock` instance:

```py
mocked_requests_200.stop()
```

Hopefully that should do it.

**Comment by lundberg** [comment]
Did it help @max-iov42 ?

**Comment by max-iov42** [comment]
Not really, I tried to what you suggested but I still got the same error. And I didn't have to time to dig deeper into the issue (I had a 
deadline until which I had to deliver my code).

My workaround was to to create a set of integration tests which run against the test system. Not pretty, but for now it works.

> Since there can be multiple RESPX mock transports started, all needs to be stopped before httpx/httpcore is unpatched.
Do I understand that right: if my test code uses more than one mock transport I have to stop all the transports? Even if the transport is not used in the test where I would like to disable it? (indeed, my my code uses more than one mock transport)

But I do not see how I can stop all of those mock transports, when I failed to stop one. I will have a look into this next weeks and see if I can get a minimal example running

The documentation could be improved regarding the `stop()/start()` feature.

**Comment by lundberg** [comment]
> The documentation could be improved regarding the `stop()/start()` feature.

Agree 👍🏻

**Comment by mh182** [comment]
Sorry I had to switch use (private account). I made a minimal example with calling `stop()` as you suggested. I still get the same error.

```python
"""Minimal example to show how to start/stop respx."""
import httpx
import respx

import pytest

API_URL = "https://en.wikipedia.org"


@pytest.fixture
def mocked_api() -> respx.MockTransport:
    with respx.mock(base_url=API_URL) as mock:
        mock.get("/api/rest_v1/page/random/summary", content={"title": "mock title"})
        yield mock


def test_stop(mocked_api: respx.MockTransport) -> None:
    mocked_api.stop()
    response = httpx.get(API_URL + "/api/rest_v1/page/random/summary")
    assert response.json() == {"title": "mock title"}
```
Calling this provide the output:
```bash
=========================================================== test session starts ============================================================
platform linux -- Python 3.8.5, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/max/work/python/respx-test
collected 1 item                                                                                                                           

tests/test_stop.py FE                                                                                                                [100%]

================================================================== ERRORS ==================================================================
______________________________________________________ ERROR at teardown of test_stop ______________________________________________________

    @pytest.fixture
    def mocked_api() -> respx.MockTransport:
        with respx.mock(base_url=API_URL) as mock:
            mock.get("/api/rest_v1/page/random/summary", content={"title": "mock title"})
>           yield mock

tests/test_stop.py:14: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../.cache/pypoetry/virtualenvs/respx-test-PE6vDkSO-py3.8/lib/python3.8/site-packages/respx/mocks.py:95: in __exit__
    self.stop()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <respx.mocks.MockTransport object at 0x7f6ba7f1a400>, clear = True, reset = True

    def stop(self, clear: bool = True, reset: bool = True) -> None:
        """
        Unregister transport and stop patching, when no registered transports left.
        """
        try:
            if self._assert_all_called:
                self.assert_all_called()
        finally:
            if clear:
                self.clear()
            if reset:
                self.reset()
    
            # Unregister current transport
>           assert self in self.transports, "RESPX transport already stopped!"
E           AssertionError: RESPX transport already stopped!

../../../.cache/pypoetry/virtualenvs/respx-test-PE6vDkSO-py3.8/lib/python3.8/site-packages/respx/mocks.py:124: AssertionError
================================================================= FAILURES =================================================================
________________________________________________________________ test_stop _________________________________________________________________

mocked_api = <respx.mocks.MockTransport object at 0x7f6ba7f1a400>

    def test_stop(mocked_api: respx.MockTransport) -> None:
>       mocked_api.stop()

tests/test_stop.py:18: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../.cache/pypoetry/virtualenvs/respx-test-PE6vDkSO-py3.8/lib/python3.8/site-packages/respx/mocks.py:116: in stop
    self.assert_all_called()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <respx.mocks.MockTransport object at 0x7f6ba7f1a400>

    def assert_all_called(self) -> None:
>       assert all(
            (pattern.called for pattern in self.patterns)
        ), "RESPX: some mocked requests were not called!"
E       AssertionError: RESPX: some mocked requests were not called!

../../../.cache/pypoetry/virtualenvs/respx-test-PE6vDkSO-py3.8/lib/python3.8/site-packages/respx/transports.py:368: AssertionError
========================================================= short test summary info ==========================================================
FAILED tests/test_stop.py::test_stop - AssertionError: RESPX: some mocked requests were not called!
ERROR tests/test_stop.py::test_stop - AssertionError: RESPX transport already stopped!
======================================================== 1 failed, 1 error in 0.13s ========================================================
```

**Comment by lundberg** [comment]
Thanks, I tried your example and now understand what's happening.

Two problems:
1. The yielded `MockTransport`, *from the fixture*, has the default [assert_all_called](https://lundberg.github.io/respx/api/#built-in-assertions) enabled, leading to the assertion failure `RESPX: some mocked requests were not called` when stopping the transport in the test...since your added/mocked url haven't been called yet.
2. The transport is stopped in the test, and then automatically stopped when leaving the context manager scope in the fixture.

This is why you see two assertion errors, *already stopped* + *not called*.

To solve your issue:
1. Configure the transport with `assert_all_called=False`.
2. Assert correct live content from the live endpoint, not `{"title": "mock title"}`.
2. Start the transport last in the test case, after the live requests has been made.

```py
import httpx
import respx

import pytest

API_URL = "https://en.wikipedia.org"


@pytest.fixture
def mocked_api() -> respx.MockTransport:
    with respx.mock(base_url=API_URL, assert_all_called=False) as mock:
        mock.get("/api/rest_v1/page/random/summary", content={"title": "mock title"})
        yield mock


def test_stop(mocked_api: respx.MockTransport) -> None:
    mocked_api.stop()
    response = httpx.get(API_URL + "/api/rest_v1/page/random/summary")
    # assert response.json() == {"title": "mock title"}
    mocked_api.stop()  # resume to not fail in fixture :-(
```

One could argue that the assertion check of stopping already stopped transport is unnecessary...I have it there only as a safety check.

**Comment by mh182** [comment]
With your example code it worked (your code just has an error to call `mocked_api.stop()` at the end of the test instead of `mocked_api.start()`).

IMHO `stop()` and `start()` should be idempotent (as for example a file `close()` is). This way we could turn on/off mocking on a "test global" level. ATM the code below fails due to the check on the double-call to `stop()`.

```python
# This flag could be turned on/off fro command line                                                                                                                                                                 
use_real_api = True                                                                                                                                                                                                 
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
@pytest.fixture                                                                                                                                                                                                     
def mocked_api() -> respx.MockTransport:                                                                                                                                                                            
    with respx.mock(base_url=API_URL, assert_all_called=False) as mock:                                                                                                                                             
        mock.get("/api/rest_v1/page/random/summary", content={"title": "mock title"})                                                                                                                               
        if use_real_api:     
            mock.stop()     
        yield mock                                                                                                                                                                                                  
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
def test_1(mocked_api: respx.MockTransport) -> None:                                       
    response = httpx.get(API_URL + "/api/rest_v1/page/random/summary")                                                                                                                                
    assert response.json() != {"title": "mock title"} 
```

**Comment by lundberg** [comment]
> With your example code it worked (your code just has an error to call `mocked_api.stop()` at the end of the test instead of `mocked_api.start()`).

Oops ;-)

> IMHO `stop()` and `start()` should be idempotent (as for example a file `close()` is) for two reasons:

Yes I agree, it should be idempotent, will do a few tests, probably nothing is affected by removing the assertion.

A side note, you could use `pass_through` to mark the mocked urls to call external real api. `respx.get(...., pass_through=True)`. This syntax is deprecated though and changed in `master` (not released) to `respx.get(...).pass_through()

**Comment by mh182** [comment]
> A side note, you could use `pass_through` to mark the mocked urls to call external real api. `respx.get(...., pass_through=True)`. This syntax is deprecated though and changed in `master` (not released) to `respx.get(...).pass_through()
Nice to know. But in my use case it would not work. I want to switch between real API service and mocked one with a flag.

BTW - thanks for the fast responses and the help you gave me. And thanks for the great work you do with the library.

**Comment by mh182** [comment]
Sorry, just saw `pass_through(bool = True)` has a flag. Yes, that would definitely work for me.

**Comment by lundberg** [comment]
> BTW - thanks for the fast responses and the help you gave me. And thanks for the great work you do with the library.

Glad to help.

Updated docs and a new release is on the way for the `master` branch.
